{castep_command: castep.serial, gnuplot_command: gnuplot,
  cell_template: template.cell, graph_path: graphs, main_relpath: .., pspot_default_termination: OTF, pspot_extension: usp, pspot_name_separator: _,
  pspot_path: data/pspot, param_template: template.param, gp_template: template.gp}
