{castep_command: castep.serial, cell_template: template.cell, default_library: castep_9_ultrasoft,
  gnuplot_command: gnuplot, gp_template: template.gp, graph_path: graphs, main_relpath: ..,
  param_template: template.param, pspot_extension: usp, pspot_name_separator: _, pspot_path: data/libraries}
