{castep_command: /home/wml08325/Desktop/castepoffrepo/CASTEP-develop.hg/obj/linux_x86_64_ifort15/castep.serial, gnuplot_command: gnuplot,
  cell_template: template.cell, graph_path: graphs, main_relpath: .., pspot_default_termination: OTF, pspot_extension: usp, pspot_name_separator: _,
  pspot_path: data/pspot, param_template: template.param, gp_template: template.gp}
